// <auto-generated />
using System;
using LCC_ENROLLMENT_SYSTEM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LCC_ENROLLMENT_SYSTEM.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class StudentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LCC_ENROLLMENT_SYSTEM.Models.Admin", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("fullname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("LCC_ENROLLMENT_SYSTEM.Models.Student", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<DateOnly>("birth_date")
                        .HasColumnType("date");

                    b.Property<string>("birth_place")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("firstname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("guardian")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("guardian_address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("guardian_phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("has_birth_certificate")
                        .HasColumnType("int");

                    b.Property<int>("has_certification")
                        .HasColumnType("int");

                    b.Property<int>("has_good_moral")
                        .HasColumnType("int");

                    b.Property<int>("has_id_picture")
                        .HasColumnType("int");

                    b.Property<int>("has_report_card")
                        .HasColumnType("int");

                    b.Property<string>("height")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("is_deleted")
                        .HasColumnType("int");

                    b.Property<string>("last_school_attended")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("last_school_year")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("middlename")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("sex")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("student_id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("weight")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
